# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  ArangoDB Documentation
baseurl: "/docs" # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username:  jekyll

url: "http://arangodb-docs.mop.aries.uberspace.de" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts
  - Dockerfile
  - todo.md
  - htmltest
  - 3.5/Examples
  - 3.4/Examples
  - 3.3/Examples
  - 3.2/Examples
  - 3.1/Examples
  - 3.0/Examples
  - 2.8/Examples
  - 3.5/allComments.txt
  - 3.4/allComments.txt
  - 3.3/allComments.txt
  - 3.2/allComments.txt
  - 3.1/allComments.txt
  - 3.0/allComments.txt
  - 2.8/allComments.txt
  # - 3.5/
  - 3.4/
  - 3.3/
  - 3.2/
  - 3.1/
  - 3.0/
  - 2.8/

versions:
  stable: "3.4"
  devel: "3.5"

